#!/bin/sh
set -eu

load_env() {
  if [ -f /etc/edge-monitor.env ]; then
    # shellcheck disable=SC1091
    . /etc/edge-monitor.env
  fi
  HOSTNAME="${HOSTNAME:-tiny01.stoffy.lan}"
  TIMEZONE="${TIMEZONE:-Africa/Johannesburg}"
  LAN_CIDRS="${LAN_CIDRS:-10.0.0.0/24,192.168.101.0/24}"
  SSH_USER="${SSH_USER:-keiki}"
  SSH_AUTHORIZED_KEYS="${SSH_AUTHORIZED_KEYS:-}"
  DISABLE_PASSWORD_SSH_IF_KEY_PRESENT="${DISABLE_PASSWORD_SSH_IF_KEY_PRESENT:-true}"
  SET_SSH_PASSWORD="${SET_SSH_PASSWORD:-true}"
  ENABLE_FIREWALL="${ENABLE_FIREWALL:-false}"
  INSTALL_ADGUARD_SYNC="${INSTALL_ADGUARD_SYNC:-true}"
  ADGUARDHOME_VERSION="${ADGUARDHOME_VERSION:-v0.107.78}"
  ADGUARDHOME_SYNC_VERSION="${ADGUARDHOME_SYNC_VERSION:-v0.9.2}"
  INSTALL_BESZEL_AGENT="${INSTALL_BESZEL_AGENT:-false}"
  BESZEL_AGENT_IMAGE="${BESZEL_AGENT_IMAGE:-henrygd/beszel-agent}"
  BESZEL_LISTEN="${BESZEL_LISTEN:-45876}"
  BESZEL_KEY="${BESZEL_KEY:-}"
  BESZEL_HUB_URL="${BESZEL_HUB_URL:-}"
  BESZEL_TOKEN="${BESZEL_TOKEN:-}"
  INSTALL_CLOUDFLARED="${INSTALL_CLOUDFLARED:-false}"
  CLOUDFLARED_IMAGE="${CLOUDFLARED_IMAGE:-cloudflare/cloudflared:2026.7.2}"
  CLOUDFLARED_TOKEN_FILE="${CLOUDFLARED_TOKEN_FILE:-/etc/cloudflared/token.env}"
  ADGUARD_UI_PORT="${ADGUARD_UI_PORT:-3000}"
  TINY_EDGE_IP="${TINY_EDGE_IP:-192.168.101.126}"
  ENABLE_SCHEDULED_CLEANUP="${ENABLE_SCHEDULED_CLEANUP:-true}"
  CLEANUP_MIN_DISK_PERCENT="${CLEANUP_MIN_DISK_PERCENT:-70}"
  CLEANUP_DOCKER_IMAGES="${CLEANUP_DOCKER_IMAGES:-true}"
  CLEANUP_DOCKER_BUILD_CACHE="${CLEANUP_DOCKER_BUILD_CACHE:-false}"
}

require_root() {
  if [ "$(id -u)" != "0" ]; then
    echo "ERROR: run as root" >&2
    exit 1
  fi
}

log() { printf '\n[edge-monitor] %s\n' "$*"; }
